/*
 * Kibernetika project, backend component
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 *
 * !!!! MANUAL REDEFINE map[string]interface{} !!!!
 */

package kclient

type ModelsArbitrary map[string]interface{}
